
server:
  port: 9095

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: Menu
          uri: lb://MENU
          predicates:
            - Path=/nic/foody/menu/**
          filters:
            - AuthenticationFilter

        - id: Order
          uri: lb://ORDER
          predicates:
            - Path=/nic/foody/orders/**
          filters:
            - AuthenticationFilter

        - id: Restaurant
          uri: lb://RESTAURANT
          predicates:
            - Path=/nic/foody/rest/**
          filters:
            - AuthenticationFilter

        - id: User
          uri: lb://USER
          predicates:
            - Path=Path= /nic/foody/user/**, /auth/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9090/eureka

